2014 Sep 15 14:18:10 EDT

ErrProgrammingError: Somebody made a mistake!
(./SRC/common/cdebug.C:118)
  File "/Users/langer/lib/homepython/oof3d/ooflib/common/worker.py", line 187, in run
    self.menuitem.callback(self, *self.args, **self.kwargs)
  File "/Users/langer/lib/homepython/oof3d/ooflib/common/IO/mainmenu.py", line 767, in _cerror
    cdebug.throwException()
  File "/Users/langer/lib/homepython/oof3d/ooflib/SWIG/common/ooferror.py", line 229, in pyErrorCallback
    exec errorstring
  File "<string>", line 1, in <module>
